plt.subplot(131),plt.imshow(normalizedimage, cmap = 'gray')
    plt.title('Input Image'), plt.xticks([]), plt.yticks([])
    # HPF=plt.imshow(img_back, cmap = 'gray')
    plt.subplot(132),plt.imshow(img_back, cmap = 'gray')
    plt.title('Image after HPF'), plt.xticks([]), plt.yticks([])
    # JET=plt.imshow(img_back)
    plt.subplot(133),plt.imshow(img_back)
    plt.title('Result in JET'), plt.xticks([]), plt.yticks([])
    plt.show()