# Generated by Django 4.0.4 on 2022-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admition_Vrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.IntegerField(auto_created=True)),
                ('aadher_number', models.IntegerField(unique=True)),
                ('dob', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('mother', models.CharField(max_length=150)),
                ('father', models.CharField(max_length=150)),
                ('income', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='csrf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sln', models.IntegerField(auto_created=True)),
                ('Roll', models.IntegerField()),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('mark3', models.IntegerField()),
                ('mark4', models.IntegerField()),
                ('mark5', models.IntegerField()),
                ('biodata1', models.CharField(editable=False, max_length=500)),
                ('biodata2', models.CharField(editable=False, max_length=500)),
                ('biodata3', models.CharField(editable=False, max_length=500)),
                ('biodata4', models.CharField(editable=False, max_length=500)),
                ('biodata5', models.CharField(editable=False, max_length=500)),
            ],
        ),
    ]
