# Generated by Django 4.0.4 on 2022-06-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admition_Vrf', '0002_admission_csrf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
    ]
