# Generated by Django 4.0.4 on 2022-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admition_Vrf', '0003_remove_admission_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='id',
        ),
        migrations.AlterField(
            model_name='admission',
            name='Roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
